import { Inter } from "next/font/google";
import "./globals.css";
import { library } from '@fortawesome/fontawesome-svg-core';
import { faArrowAltCircleDown } from '@fortawesome/free-solid-svg-icons'; // Replace `faIconName` with the icon you want to use

library.add(faArrowAltCircleDown);
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
